// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"classroom-analysis/internal/ioc"
	"classroom-analysis/internal/repository"
	"classroom-analysis/internal/repository/dao"
	"classroom-analysis/internal/service"
	"classroom-analysis/internal/web"
)

// Injectors from wire.go:

func InitWebServer() *App {
	client := ioc.InitMongodb()
	v := ioc.InitLogger(client)
	emailDaoInterface := dao.NewEmailDao(client)
	emailInterface := repository.NewEmailRepository(emailDaoInterface)
	emailServiceInterface := service.NewEmailService(emailInterface)
	emailHandler := web.NewEmailHandler(emailServiceInterface)
	database := ioc.InitMongoDatabase(client)
	teacherDAO := dao.NewTeacherDAO(database)
	teacherRepository := repository.NewTeacherRepository(teacherDAO)
	analysisDAO := dao.NewAnalysisDAO(database)
	analysisRepository := repository.NewAnalysisRepository(analysisDAO, emailDaoInterface)
	videoAnalysisDAO := dao.NewVideoAnalysisDAO(database)
	videoAnalysisRepository := repository.NewVideoAnalysisRepository(videoAnalysisDAO)
	studentDAO := dao.NewStudentDAO(database)
	studentRepository := repository.NewStudentRepository(studentDAO)
	studentFocusDAO := dao.NewStudentFocusDAO(database)
	studentFocusRepository := repository.NewStudentFocusRepository(studentFocusDAO)
	teacherService := service.NewTeacherService(teacherRepository, analysisRepository, videoAnalysisRepository, studentRepository, studentFocusRepository)
	imageAnalysisDAO := dao.NewImageAnalysisDAO(database)
	imageAnalysisRepository := repository.NewImageAnalysisRepository(imageAnalysisDAO)
	analysisTaskDAO := dao.NewAnalysisTaskDAO(database)
	analysisTaskRepository := repository.NewAnalysisTaskRepository(analysisTaskDAO)
	faceAnalysisDAO := dao.NewFaceAnalysisDAO(database)
	faceAnalysisRepository := repository.NewFaceAnalysisRepository(faceAnalysisDAO)
	analysisService := service.NewAnalysisService(analysisRepository, videoAnalysisRepository, imageAnalysisRepository, studentFocusRepository, studentRepository, analysisTaskRepository, faceAnalysisRepository)
	logger := ioc.NewLogger()
	writer := ioc.InitKafkaWriter()
	redisClient := ioc.InitRedis()
	teacherHandler := web.NewTeacherHandler(teacherService, analysisService, logger, writer, redisClient)
	minioClient := ioc.NewMinioClient()
	fileDao := dao.NewFileDao(database)
	fileDaoInterface := dao.ProvideFileDaoInterface(fileDao)
	fileRepository := repository.NewFileRepository(fileDaoInterface)
	fileInterface := repository.ProvideFileInterface(fileRepository)
	fileServiceInterface := service.NewFileService(minioClient, fileInterface)
	fileHandler := web.NewFileHandler(fileServiceInterface)
	engine := ioc.InitGin(v, emailHandler, teacherHandler, fileHandler)
	config := ioc.InitViper()
	app := &App{
		server:      engine,
		mongodb:     client,
		redis:       redisClient,
		minio:       minioClient,
		config:      config,
		FileHandler: fileHandler,
	}
	return app
}
